theme: jekyll-theme-cayman
title: Welcome to my homepage!
description: If you want to track my updates, bookmark this page!
{% if page.show_sidebar %}
  <div class="sidebar">
    sidebar content
  </div>
{% endif %}
